### ISSUE TITLE
Error in custom_header.php

### ISSUE THREAD

**Issue by huskybiped** [Manoz/split-me#1]
Default installation threw an error for me:

Parse error: syntax error, unexpected '[' in /home/husky/meowkitty.com/wp-content/themes/split-me/inc/custom-header.php on line 30

This is the following:
 $img = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'large' )[1];

I was able to fix it by just removing the [1], but probably not the correct way to fix..

**Comment by Manoz** [comment]
Hello,

This is strange. I have not been able to reproduce the error.
By default, this value is `[0]` , not `[1]` as you can see in [this file](https://github.com/Manoz/split-me/blob/master/split-me/inc/custom-header.php#L30).

What is your WordPress version?

**Comment by sylwit** [comment]
I guess it's most a PHP version matter

wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'large' )[1]; should be available in PHP 5.4

**Comment by Manoz** [comment]
Not sure. I have some errors in the 404 page because of this function. I tryed this but it's the same problem:

```
elseif ( has_post_thumbnail() ) {
    global $post;
    $img = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'large' );
    $custom_css = "
.sm-inner-h {
    background: linear-gradient(
        to bottom, rgba(0, 0, 0, 0.4) 0%, transparent 30%),
        url('{$img[0]}');
    background-position: center 30%;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
}
    ";
}
```

**Comment by Manoz** [comment]
Hello again @huskybiped . I think I fixed the issue. I have no more errors. Can you try the new `split-me.zip`? The array still return the `[0]` value wich is the thumbnail url.

**Comment by huskybiped** [comment]
Hello @Manoz @sylwit  - I installed the latest version with the changes, and it did not actually solve the problem.  I did see the comment about PHP version and found that the default dreamhost version is PHP 5.3 (fast-cgi).   I updated the version to PHP 5.4 (fast-cgi) and found that it resolved the problem.   

On a side note, I mistyped the [1] above.   It would not work with either [1] or [0].  I had changed it to try to see what info was coming from the array.

**Comment by PofMagicfingers** [comment]
Not tested, but pretty sure you can fix it for every PHP versions, by wrapping the call in parenthesis :

`$img = (wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'large' ))[1];`

**Comment by Manoz** [comment]
The solution was hard to find. When we are in a 404 or a archive page, the `global $post;` don't work like another page. The `$post` is NULL.

The problem should be fixed in the 2 last commits. Can you try with the last `split-me.zip` file? :)
I have added the details in the `custom_header.php` file (see the comments)

**Comment by huskybiped** [comment]
@PofMagicfingers  - I just tested with PHP 5.3 while wrapping the call in the parenthesis as suggested.  It did not solve the error.

**Comment by Manoz** [comment]
@huskybiped Can you try with the last .zip pls? it should work now :)

**Comment by huskybiped** [comment]
@Manoz  - Sure, I just tested and got a new error:

```
Parse error: syntax error, unexpected '[' in /home/husky/meowkitty.com/wp-content/themes/split-me/inc/custom-header.php on line 20
```

That is this line:

```
       wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'large' )[0] :
```

Again, it all seems to work fine now when using PHP 5.4.   It just has the problem on PHP 5.3.

**Comment by Manoz** [comment]
Ok so, for this problem, it's because of PHP 5.3. I should find a way to write a condition for earlier versions of php. I close this incident, thank you :)

**Comment by Manoz** [comment]
EDIT: this error with older versions of PHP is now definitely fixed with the version `1.0.7` of **Split Me** \o/

**Comment by huskybiped** [comment]
Thanks very much!
